'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PosRT_Cabang
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ChekVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InitSchemaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InfoPosrtOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportSalesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportStockolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTaskOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTaskCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTrPrCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFileInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFileInfoCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ACKTaskCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ACKFileInfoCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResetTableHOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResetTableCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CheckConnectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportSalesCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetStatusTableOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RestoreTableOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DownloadMasterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DownloadTblTokoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InquiryRetTokOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UploadRetTokOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendTokoUpOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecuteQueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertTrPrCabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TrPrCabang.My.MySettings.Default.TrPrCabang_PosRT_Cabang_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ChekVersionCompleted As ChekVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event InitSchemaCompleted As InitSchemaCompletedEventHandler
        
        '''<remarks/>
        Public Event InfoPosrtCompleted As InfoPosrtCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportSalesCompleted As ReportSalesCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportStockolCompleted As ReportStockolCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTaskCompleted As GetTaskCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTaskCabCompleted As GetTaskCabCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTrPrCabCompleted As GetTrPrCabCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFileInfoCompleted As GetFileInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFileInfoCabCompleted As GetFileInfoCabCompletedEventHandler
        
        '''<remarks/>
        Public Event ACKTaskCabCompleted As ACKTaskCabCompletedEventHandler
        
        '''<remarks/>
        Public Event ACKFileInfoCabCompleted As ACKFileInfoCabCompletedEventHandler
        
        '''<remarks/>
        Public Event ResetTableHOCompleted As ResetTableHOCompletedEventHandler
        
        '''<remarks/>
        Public Event ResetTableCabCompleted As ResetTableCabCompletedEventHandler
        
        '''<remarks/>
        Public Event CheckConnectionCompleted As CheckConnectionCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportSalesCabCompleted As ReportSalesCabCompletedEventHandler
        
        '''<remarks/>
        Public Event GetStatusTableCompleted As GetStatusTableCompletedEventHandler
        
        '''<remarks/>
        Public Event RestoreTableCompleted As RestoreTableCompletedEventHandler
        
        '''<remarks/>
        Public Event DownloadMasterCompleted As DownloadMasterCompletedEventHandler
        
        '''<remarks/>
        Public Event DownloadTblTokoCompleted As DownloadTblTokoCompletedEventHandler
        
        '''<remarks/>
        Public Event SendStatusCompleted As SendStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event InquiryRetTokCompleted As InquiryRetTokCompletedEventHandler
        
        '''<remarks/>
        Public Event UploadRetTokCompleted As UploadRetTokCompletedEventHandler
        
        '''<remarks/>
        Public Event SendTokoUpCompleted As SendTokoUpCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecuteQueryCompleted As ExecuteQueryCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertTrPrCabCompleted As InsertTrPrCabCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChekVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChekVersion() As String
            Dim results() As Object = Me.Invoke("ChekVersion", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChekVersionAsync()
            Me.ChekVersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChekVersionAsync(ByVal userState As Object)
            If (Me.ChekVersionOperationCompleted Is Nothing) Then
                Me.ChekVersionOperationCompleted = AddressOf Me.OnChekVersionOperationCompleted
            End If
            Me.InvokeAsync("ChekVersion", New Object(-1) {}, Me.ChekVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnChekVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChekVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChekVersionCompleted(Me, New ChekVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InitSchema", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InitSchema() As String
            Dim results() As Object = Me.Invoke("InitSchema", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InitSchemaAsync()
            Me.InitSchemaAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InitSchemaAsync(ByVal userState As Object)
            If (Me.InitSchemaOperationCompleted Is Nothing) Then
                Me.InitSchemaOperationCompleted = AddressOf Me.OnInitSchemaOperationCompleted
            End If
            Me.InvokeAsync("InitSchema", New Object(-1) {}, Me.InitSchemaOperationCompleted, userState)
        End Sub
        
        Private Sub OnInitSchemaOperationCompleted(ByVal arg As Object)
            If (Not (Me.InitSchemaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InitSchemaCompleted(Me, New InitSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InfoPosrt", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InfoPosrt(ByVal KdToko As String)
            Me.Invoke("InfoPosrt", New Object() {KdToko})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InfoPosrtAsync(ByVal KdToko As String)
            Me.InfoPosrtAsync(KdToko, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InfoPosrtAsync(ByVal KdToko As String, ByVal userState As Object)
            If (Me.InfoPosrtOperationCompleted Is Nothing) Then
                Me.InfoPosrtOperationCompleted = AddressOf Me.OnInfoPosrtOperationCompleted
            End If
            Me.InvokeAsync("InfoPosrt", New Object() {KdToko}, Me.InfoPosrtOperationCompleted, userState)
        End Sub
        
        Private Sub OnInfoPosrtOperationCompleted(ByVal arg As Object)
            If (Not (Me.InfoPosrtCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InfoPosrtCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportSales", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportSales(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("ReportSales", New Object() {Data, CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportSalesAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.ReportSalesAsync(Data, CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportSalesAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.ReportSalesOperationCompleted Is Nothing) Then
                Me.ReportSalesOperationCompleted = AddressOf Me.OnReportSalesOperationCompleted
            End If
            Me.InvokeAsync("ReportSales", New Object() {Data, CredToko, CredCabang}, Me.ReportSalesOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportSalesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportSalesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportSalesCompleted(Me, New ReportSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportStockol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportStockol(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Data() As Byte) As String
            Dim results() As Object = Me.Invoke("ReportStockol", New Object() {Data})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportStockolAsync(ByVal Data() As Byte)
            Me.ReportStockolAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportStockolAsync(ByVal Data() As Byte, ByVal userState As Object)
            If (Me.ReportStockolOperationCompleted Is Nothing) Then
                Me.ReportStockolOperationCompleted = AddressOf Me.OnReportStockolOperationCompleted
            End If
            Me.InvokeAsync("ReportStockol", New Object() {Data}, Me.ReportStockolOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportStockolOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportStockolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportStockolCompleted(Me, New ReportStockolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTask", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTask(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetTask", New Object() {CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTaskAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.GetTaskAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTaskAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.GetTaskOperationCompleted Is Nothing) Then
                Me.GetTaskOperationCompleted = AddressOf Me.OnGetTaskOperationCompleted
            End If
            Me.InvokeAsync("GetTask", New Object() {CredToko, CredCabang}, Me.GetTaskOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTaskOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTaskCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTaskCompleted(Me, New GetTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTaskCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTaskCab(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetTaskCab", New Object() {CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTaskCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.GetTaskCabAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTaskCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.GetTaskCabOperationCompleted Is Nothing) Then
                Me.GetTaskCabOperationCompleted = AddressOf Me.OnGetTaskCabOperationCompleted
            End If
            Me.InvokeAsync("GetTaskCab", New Object() {CredToko, CredCabang}, Me.GetTaskCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTaskCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTaskCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTaskCabCompleted(Me, New GetTaskCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTrPrCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTrPrCab(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetTrPrCab", New Object() {CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTrPrCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.GetTrPrCabAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTrPrCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.GetTrPrCabOperationCompleted Is Nothing) Then
                Me.GetTrPrCabOperationCompleted = AddressOf Me.OnGetTrPrCabOperationCompleted
            End If
            Me.InvokeAsync("GetTrPrCab", New Object() {CredToko, CredCabang}, Me.GetTrPrCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTrPrCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTrPrCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTrPrCabCompleted(Me, New GetTrPrCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFileInfo(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetFileInfo", New Object() {CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.GetFileInfoAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.GetFileInfoOperationCompleted Is Nothing) Then
                Me.GetFileInfoOperationCompleted = AddressOf Me.OnGetFileInfoOperationCompleted
            End If
            Me.InvokeAsync("GetFileInfo", New Object() {CredToko, CredCabang}, Me.GetFileInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFileInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFileInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFileInfoCompleted(Me, New GetFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFileInfoCab(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetFileInfoCab", New Object() {CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.GetFileInfoCabAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.GetFileInfoCabOperationCompleted Is Nothing) Then
                Me.GetFileInfoCabOperationCompleted = AddressOf Me.OnGetFileInfoCabOperationCompleted
            End If
            Me.InvokeAsync("GetFileInfoCab", New Object() {CredToko, CredCabang}, Me.GetFileInfoCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFileInfoCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFileInfoCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFileInfoCabCompleted(Me, New GetFileInfoCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ACKTaskCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ACKTaskCab(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As Boolean
            Dim results() As Object = Me.Invoke("ACKTaskCab", New Object() {Data, CredToko, CredCabang})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ACKTaskCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.ACKTaskCabAsync(Data, CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ACKTaskCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.ACKTaskCabOperationCompleted Is Nothing) Then
                Me.ACKTaskCabOperationCompleted = AddressOf Me.OnACKTaskCabOperationCompleted
            End If
            Me.InvokeAsync("ACKTaskCab", New Object() {Data, CredToko, CredCabang}, Me.ACKTaskCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnACKTaskCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ACKTaskCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ACKTaskCabCompleted(Me, New ACKTaskCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ACKFileInfoCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ACKFileInfoCab(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As Boolean
            Dim results() As Object = Me.Invoke("ACKFileInfoCab", New Object() {Data, CredToko, CredCabang})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ACKFileInfoCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.ACKFileInfoCabAsync(Data, CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ACKFileInfoCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.ACKFileInfoCabOperationCompleted Is Nothing) Then
                Me.ACKFileInfoCabOperationCompleted = AddressOf Me.OnACKFileInfoCabOperationCompleted
            End If
            Me.InvokeAsync("ACKFileInfoCab", New Object() {Data, CredToko, CredCabang}, Me.ACKFileInfoCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnACKFileInfoCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ACKFileInfoCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ACKFileInfoCabCompleted(Me, New ACKFileInfoCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetTableHO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ResetTableHO(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As String
            Dim results() As Object = Me.Invoke("ResetTableHO", New Object() {CredToko, CredCabang})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ResetTableHOAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.ResetTableHOAsync(CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResetTableHOAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.ResetTableHOOperationCompleted Is Nothing) Then
                Me.ResetTableHOOperationCompleted = AddressOf Me.OnResetTableHOOperationCompleted
            End If
            Me.InvokeAsync("ResetTableHO", New Object() {CredToko, CredCabang}, Me.ResetTableHOOperationCompleted, userState)
        End Sub
        
        Private Sub OnResetTableHOOperationCompleted(ByVal arg As Object)
            If (Not (Me.ResetTableHOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ResetTableHOCompleted(Me, New ResetTableHOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetTableCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ResetTableCab(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal Jenis As String) As String
            Dim results() As Object = Me.Invoke("ResetTableCab", New Object() {CredToko, CredCabang, Jenis})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ResetTableCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal Jenis As String)
            Me.ResetTableCabAsync(CredToko, CredCabang, Jenis, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResetTableCabAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal Jenis As String, ByVal userState As Object)
            If (Me.ResetTableCabOperationCompleted Is Nothing) Then
                Me.ResetTableCabOperationCompleted = AddressOf Me.OnResetTableCabOperationCompleted
            End If
            Me.InvokeAsync("ResetTableCab", New Object() {CredToko, CredCabang, Jenis}, Me.ResetTableCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnResetTableCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ResetTableCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ResetTableCabCompleted(Me, New ResetTableCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckConnection(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal KeyToko_IMSI As String) As String
            Dim results() As Object = Me.Invoke("CheckConnection", New Object() {CredToko, CredCabang, KeyToko_IMSI})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckConnectionAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal KeyToko_IMSI As String)
            Me.CheckConnectionAsync(CredToko, CredCabang, KeyToko_IMSI, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckConnectionAsync(ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal KeyToko_IMSI As String, ByVal userState As Object)
            If (Me.CheckConnectionOperationCompleted Is Nothing) Then
                Me.CheckConnectionOperationCompleted = AddressOf Me.OnCheckConnectionOperationCompleted
            End If
            Me.InvokeAsync("CheckConnection", New Object() {CredToko, CredCabang, KeyToko_IMSI}, Me.CheckConnectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckConnectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckConnectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckConnectionCompleted(Me, New CheckConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportSalesCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportSalesCab(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("ReportSalesCab", New Object() {Data, CredToko, CredCabang})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportSalesCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.ReportSalesCabAsync(Data, CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportSalesCabAsync(ByVal Data() As Byte, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.ReportSalesCabOperationCompleted Is Nothing) Then
                Me.ReportSalesCabOperationCompleted = AddressOf Me.OnReportSalesCabOperationCompleted
            End If
            Me.InvokeAsync("ReportSalesCab", New Object() {Data, CredToko, CredCabang}, Me.ReportSalesCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportSalesCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportSalesCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportSalesCabCompleted(Me, New ReportSalesCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatusTable", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStatusTable(ByVal ListToko As String, ByVal KdCabang As String, ByVal NamaTable As String, ByVal Status As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetStatusTable", New Object() {ListToko, KdCabang, NamaTable, Status})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStatusTableAsync(ByVal ListToko As String, ByVal KdCabang As String, ByVal NamaTable As String, ByVal Status As String)
            Me.GetStatusTableAsync(ListToko, KdCabang, NamaTable, Status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStatusTableAsync(ByVal ListToko As String, ByVal KdCabang As String, ByVal NamaTable As String, ByVal Status As String, ByVal userState As Object)
            If (Me.GetStatusTableOperationCompleted Is Nothing) Then
                Me.GetStatusTableOperationCompleted = AddressOf Me.OnGetStatusTableOperationCompleted
            End If
            Me.InvokeAsync("GetStatusTable", New Object() {ListToko, KdCabang, NamaTable, Status}, Me.GetStatusTableOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStatusTableOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStatusTableCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStatusTableCompleted(Me, New GetStatusTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RestoreTable", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RestoreTable(ByVal KodeToko As String, ByVal TblName As String, ByVal DayInterval As Integer) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("RestoreTable", New Object() {KodeToko, TblName, DayInterval})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RestoreTableAsync(ByVal KodeToko As String, ByVal TblName As String, ByVal DayInterval As Integer)
            Me.RestoreTableAsync(KodeToko, TblName, DayInterval, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RestoreTableAsync(ByVal KodeToko As String, ByVal TblName As String, ByVal DayInterval As Integer, ByVal userState As Object)
            If (Me.RestoreTableOperationCompleted Is Nothing) Then
                Me.RestoreTableOperationCompleted = AddressOf Me.OnRestoreTableOperationCompleted
            End If
            Me.InvokeAsync("RestoreTable", New Object() {KodeToko, TblName, DayInterval}, Me.RestoreTableOperationCompleted, userState)
        End Sub
        
        Private Sub OnRestoreTableOperationCompleted(ByVal arg As Object)
            If (Not (Me.RestoreTableCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RestoreTableCompleted(Me, New RestoreTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadMaster", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DownloadMaster(ByVal NamaTbl As String, ByVal TglMin As Date) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("DownloadMaster", New Object() {NamaTbl, TglMin})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DownloadMasterAsync(ByVal NamaTbl As String, ByVal TglMin As Date)
            Me.DownloadMasterAsync(NamaTbl, TglMin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DownloadMasterAsync(ByVal NamaTbl As String, ByVal TglMin As Date, ByVal userState As Object)
            If (Me.DownloadMasterOperationCompleted Is Nothing) Then
                Me.DownloadMasterOperationCompleted = AddressOf Me.OnDownloadMasterOperationCompleted
            End If
            Me.InvokeAsync("DownloadMaster", New Object() {NamaTbl, TglMin}, Me.DownloadMasterOperationCompleted, userState)
        End Sub
        
        Private Sub OnDownloadMasterOperationCompleted(ByVal arg As Object)
            If (Not (Me.DownloadMasterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DownloadMasterCompleted(Me, New DownloadMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadTblToko", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DownloadTblToko(ByVal CredToko As TokoCredentials) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("DownloadTblToko", New Object() {CredToko})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DownloadTblTokoAsync(ByVal CredToko As TokoCredentials)
            Me.DownloadTblTokoAsync(CredToko, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DownloadTblTokoAsync(ByVal CredToko As TokoCredentials, ByVal userState As Object)
            If (Me.DownloadTblTokoOperationCompleted Is Nothing) Then
                Me.DownloadTblTokoOperationCompleted = AddressOf Me.OnDownloadTblTokoOperationCompleted
            End If
            Me.InvokeAsync("DownloadTblToko", New Object() {CredToko}, Me.DownloadTblTokoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDownloadTblTokoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DownloadTblTokoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DownloadTblTokoCompleted(Me, New DownloadTblTokoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendStatus(ByVal Status As StatusToko) As StatusToko
            Dim results() As Object = Me.Invoke("SendStatus", New Object() {Status})
            Return CType(results(0),StatusToko)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendStatusAsync(ByVal Status As StatusToko)
            Me.SendStatusAsync(Status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendStatusAsync(ByVal Status As StatusToko, ByVal userState As Object)
            If (Me.SendStatusOperationCompleted Is Nothing) Then
                Me.SendStatusOperationCompleted = AddressOf Me.OnSendStatusOperationCompleted
            End If
            Me.InvokeAsync("SendStatus", New Object() {Status}, Me.SendStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendStatusCompleted(Me, New SendStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InquiryRetTok", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InquiryRetTok(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal RequestRET() As Byte) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("InquiryRetTok", New Object() {RequestRET})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub InquiryRetTokAsync(ByVal RequestRET() As Byte)
            Me.InquiryRetTokAsync(RequestRET, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InquiryRetTokAsync(ByVal RequestRET() As Byte, ByVal userState As Object)
            If (Me.InquiryRetTokOperationCompleted Is Nothing) Then
                Me.InquiryRetTokOperationCompleted = AddressOf Me.OnInquiryRetTokOperationCompleted
            End If
            Me.InvokeAsync("InquiryRetTok", New Object() {RequestRET}, Me.InquiryRetTokOperationCompleted, userState)
        End Sub
        
        Private Sub OnInquiryRetTokOperationCompleted(ByVal arg As Object)
            If (Not (Me.InquiryRetTokCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InquiryRetTokCompleted(Me, New InquiryRetTokCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadRetTok", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UploadRetTok(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal RequestRET() As Byte) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("UploadRetTok", New Object() {RequestRET})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub UploadRetTokAsync(ByVal RequestRET() As Byte)
            Me.UploadRetTokAsync(RequestRET, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UploadRetTokAsync(ByVal RequestRET() As Byte, ByVal userState As Object)
            If (Me.UploadRetTokOperationCompleted Is Nothing) Then
                Me.UploadRetTokOperationCompleted = AddressOf Me.OnUploadRetTokOperationCompleted
            End If
            Me.InvokeAsync("UploadRetTok", New Object() {RequestRET}, Me.UploadRetTokOperationCompleted, userState)
        End Sub
        
        Private Sub OnUploadRetTokOperationCompleted(ByVal arg As Object)
            If (Not (Me.UploadRetTokCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UploadRetTokCompleted(Me, New UploadRetTokCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTokoUp", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendTokoUp(ByVal KodeCabang As String, ByVal TotalToko As String, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials) As String
            Dim results() As Object = Me.Invoke("SendTokoUp", New Object() {KodeCabang, TotalToko, CredToko, CredCabang})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendTokoUpAsync(ByVal KodeCabang As String, ByVal TotalToko As String, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials)
            Me.SendTokoUpAsync(KodeCabang, TotalToko, CredToko, CredCabang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendTokoUpAsync(ByVal KodeCabang As String, ByVal TotalToko As String, ByVal CredToko As TokoCredentials, ByVal CredCabang As CabangCredentials, ByVal userState As Object)
            If (Me.SendTokoUpOperationCompleted Is Nothing) Then
                Me.SendTokoUpOperationCompleted = AddressOf Me.OnSendTokoUpOperationCompleted
            End If
            Me.InvokeAsync("SendTokoUp", New Object() {KodeCabang, TotalToko, CredToko, CredCabang}, Me.SendTokoUpOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendTokoUpOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendTokoUpCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendTokoUpCompleted(Me, New SendTokoUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteQuery", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteQuery(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Query() As Byte) As String
            Dim results() As Object = Me.Invoke("ExecuteQuery", New Object() {Query})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuteQueryAsync(ByVal Query() As Byte)
            Me.ExecuteQueryAsync(Query, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuteQueryAsync(ByVal Query() As Byte, ByVal userState As Object)
            If (Me.ExecuteQueryOperationCompleted Is Nothing) Then
                Me.ExecuteQueryOperationCompleted = AddressOf Me.OnExecuteQueryOperationCompleted
            End If
            Me.InvokeAsync("ExecuteQuery", New Object() {Query}, Me.ExecuteQueryOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuteQueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuteQueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuteQueryCompleted(Me, New ExecuteQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertTrPrCab", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertTrPrCab(ByVal TaskName As String, ByVal Toko As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Cmd() As Byte) As String
            Dim results() As Object = Me.Invoke("InsertTrPrCab", New Object() {TaskName, Toko, Cmd})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertTrPrCabAsync(ByVal TaskName As String, ByVal Toko As String, ByVal Cmd() As Byte)
            Me.InsertTrPrCabAsync(TaskName, Toko, Cmd, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertTrPrCabAsync(ByVal TaskName As String, ByVal Toko As String, ByVal Cmd() As Byte, ByVal userState As Object)
            If (Me.InsertTrPrCabOperationCompleted Is Nothing) Then
                Me.InsertTrPrCabOperationCompleted = AddressOf Me.OnInsertTrPrCabOperationCompleted
            End If
            Me.InvokeAsync("InsertTrPrCab", New Object() {TaskName, Toko, Cmd}, Me.InsertTrPrCabOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertTrPrCabOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertTrPrCabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertTrPrCabCompleted(Me, New InsertTrPrCabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TokoCredentials
        
        Private kodeTokoField As String
        
        Private ipAddressField As String
        
        Private stationField As String
        
        Private logTimeField As Date
        
        Private signatureField As String
        
        '''<remarks/>
        Public Property KodeToko() As String
            Get
                Return Me.kodeTokoField
            End Get
            Set
                Me.kodeTokoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Station() As String
            Get
                Return Me.stationField
            End Get
            Set
                Me.stationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LogTime() As Date
            Get
                Return Me.logTimeField
            End Get
            Set
                Me.logTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Signature() As String
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StatusToko
        
        Private kodeTokoField As String
        
        Private kodeField As String
        
        Private ref1Field As String
        
        Private ref2Field As String
        
        Private ref3Field As String
        
        Private ref4Field As String
        
        Private ref5Field As String
        
        Private statusField As String
        
        Private ipTokoField As String
        
        Private errCodeField As Integer
        
        Private errDetailField As String
        
        '''<remarks/>
        Public Property KodeToko() As String
            Get
                Return Me.kodeTokoField
            End Get
            Set
                Me.kodeTokoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kode() As String
            Get
                Return Me.kodeField
            End Get
            Set
                Me.kodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ref1() As String
            Get
                Return Me.ref1Field
            End Get
            Set
                Me.ref1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ref2() As String
            Get
                Return Me.ref2Field
            End Get
            Set
                Me.ref2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ref3() As String
            Get
                Return Me.ref3Field
            End Get
            Set
                Me.ref3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ref4() As String
            Get
                Return Me.ref4Field
            End Get
            Set
                Me.ref4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ref5() As String
            Get
                Return Me.ref5Field
            End Get
            Set
                Me.ref5Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IpToko() As String
            Get
                Return Me.ipTokoField
            End Get
            Set
                Me.ipTokoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrCode() As Integer
            Get
                Return Me.errCodeField
            End Get
            Set
                Me.errCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrDetail() As String
            Get
                Return Me.errDetailField
            End Get
            Set
                Me.errDetailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CabangCredentials
        
        Private kodeCabangField As String
        
        Private ipAddressField As String
        
        Private logTimeField As Date
        
        Private signatureField As String
        
        '''<remarks/>
        Public Property KodeCabang() As String
            Get
                Return Me.kodeCabangField
            End Get
            Set
                Me.kodeCabangField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IpAddress() As String
            Get
                Return Me.ipAddressField
            End Get
            Set
                Me.ipAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LogTime() As Date
            Get
                Return Me.logTimeField
            End Get
            Set
                Me.logTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Signature() As String
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ChekVersionCompletedEventHandler(ByVal sender As Object, ByVal e As ChekVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChekVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InitSchemaCompletedEventHandler(ByVal sender As Object, ByVal e As InitSchemaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InitSchemaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InfoPosrtCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReportSalesCompletedEventHandler(ByVal sender As Object, ByVal e As ReportSalesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportSalesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReportStockolCompletedEventHandler(ByVal sender As Object, ByVal e As ReportStockolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportStockolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetTaskCompletedEventHandler(ByVal sender As Object, ByVal e As GetTaskCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTaskCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetTaskCabCompletedEventHandler(ByVal sender As Object, ByVal e As GetTaskCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTaskCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetTrPrCabCompletedEventHandler(ByVal sender As Object, ByVal e As GetTrPrCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTrPrCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetFileInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetFileInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFileInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetFileInfoCabCompletedEventHandler(ByVal sender As Object, ByVal e As GetFileInfoCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFileInfoCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ACKTaskCabCompletedEventHandler(ByVal sender As Object, ByVal e As ACKTaskCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ACKTaskCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ACKFileInfoCabCompletedEventHandler(ByVal sender As Object, ByVal e As ACKFileInfoCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ACKFileInfoCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ResetTableHOCompletedEventHandler(ByVal sender As Object, ByVal e As ResetTableHOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ResetTableHOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ResetTableCabCompletedEventHandler(ByVal sender As Object, ByVal e As ResetTableCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ResetTableCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CheckConnectionCompletedEventHandler(ByVal sender As Object, ByVal e As CheckConnectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckConnectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReportSalesCabCompletedEventHandler(ByVal sender As Object, ByVal e As ReportSalesCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportSalesCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetStatusTableCompletedEventHandler(ByVal sender As Object, ByVal e As GetStatusTableCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStatusTableCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RestoreTableCompletedEventHandler(ByVal sender As Object, ByVal e As RestoreTableCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RestoreTableCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DownloadMasterCompletedEventHandler(ByVal sender As Object, ByVal e As DownloadMasterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DownloadMasterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DownloadTblTokoCompletedEventHandler(ByVal sender As Object, ByVal e As DownloadTblTokoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DownloadTblTokoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendStatusCompletedEventHandler(ByVal sender As Object, ByVal e As SendStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StatusToko
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StatusToko)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InquiryRetTokCompletedEventHandler(ByVal sender As Object, ByVal e As InquiryRetTokCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InquiryRetTokCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UploadRetTokCompletedEventHandler(ByVal sender As Object, ByVal e As UploadRetTokCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UploadRetTokCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendTokoUpCompletedEventHandler(ByVal sender As Object, ByVal e As SendTokoUpCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendTokoUpCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ExecuteQueryCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuteQueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuteQueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InsertTrPrCabCompletedEventHandler(ByVal sender As Object, ByVal e As InsertTrPrCabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertTrPrCabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
