//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectedServices_PosRT_Cabang
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConnectedServices_PosRT_Cabang.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChekVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ChekVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> InitSchemaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoPosrt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task InfoPosrtAsync(string KdToko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesResponse> ReportSalesAsync(ConnectedServices_PosRT_Cabang.ReportSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportStockol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportStockolResponse> ReportStockolAsync(ConnectedServices_PosRT_Cabang.ReportStockolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskResponse> GetTaskAsync(ConnectedServices_PosRT_Cabang.GetTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaskCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskCabResponse> GetTaskCabAsync(ConnectedServices_PosRT_Cabang.GetTaskCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrPrCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTrPrCabResponse> GetTrPrCabAsync(ConnectedServices_PosRT_Cabang.GetTrPrCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoResponse> GetFileInfoAsync(ConnectedServices_PosRT_Cabang.GetFileInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileInfoCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoCabResponse> GetFileInfoCabAsync(ConnectedServices_PosRT_Cabang.GetFileInfoCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACKTaskCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKTaskCabResponse> ACKTaskCabAsync(ConnectedServices_PosRT_Cabang.ACKTaskCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACKFileInfoCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKFileInfoCabResponse> ACKFileInfoCabAsync(ConnectedServices_PosRT_Cabang.ACKFileInfoCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetTableHO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ResetTableHOAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetTableCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ResetTableCabAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang, string Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckConnectionAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang, string KeyToko_IMSI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportSalesCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesCabResponse> ReportSalesCabAsync(ConnectedServices_PosRT_Cabang.ReportSalesCabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatusTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetStatusTableResponse> GetStatusTableAsync(ConnectedServices_PosRT_Cabang.GetStatusTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestoreTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.RestoreTableResponse> RestoreTableAsync(ConnectedServices_PosRT_Cabang.RestoreTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadMasterResponse> DownloadMasterAsync(ConnectedServices_PosRT_Cabang.DownloadMasterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadTblToko", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadTblTokoResponse> DownloadTblTokoAsync(ConnectedServices_PosRT_Cabang.DownloadTblTokoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.StatusToko> SendStatusAsync(ConnectedServices_PosRT_Cabang.StatusToko Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquiryRetTok", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InquiryRetTokResponse> InquiryRetTokAsync(ConnectedServices_PosRT_Cabang.InquiryRetTokRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadRetTok", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.UploadRetTokResponse> UploadRetTokAsync(ConnectedServices_PosRT_Cabang.UploadRetTokRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTokoUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendTokoUpAsync(string KodeCabang, string TotalToko, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ExecuteQueryResponse> ExecuteQueryAsync(ConnectedServices_PosRT_Cabang.ExecuteQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTrPrCab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InsertTrPrCabResponse> InsertTrPrCabAsync(ConnectedServices_PosRT_Cabang.InsertTrPrCabRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokoCredentials
    {
        
        private string kodeTokoField;
        
        private string ipAddressField;
        
        private string stationField;
        
        private System.DateTime logTimeField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KodeToko
        {
            get
            {
                return this.kodeTokoField;
            }
            set
            {
                this.kodeTokoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IpAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Station
        {
            get
            {
                return this.stationField;
            }
            set
            {
                this.stationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime LogTime
        {
            get
            {
                return this.logTimeField;
            }
            set
            {
                this.logTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusToko
    {
        
        private string kodeTokoField;
        
        private string kodeField;
        
        private string ref1Field;
        
        private string ref2Field;
        
        private string ref3Field;
        
        private string ref4Field;
        
        private string ref5Field;
        
        private string statusField;
        
        private string ipTokoField;
        
        private int errCodeField;
        
        private string errDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KodeToko
        {
            get
            {
                return this.kodeTokoField;
            }
            set
            {
                this.kodeTokoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kode
        {
            get
            {
                return this.kodeField;
            }
            set
            {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ref1
        {
            get
            {
                return this.ref1Field;
            }
            set
            {
                this.ref1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ref2
        {
            get
            {
                return this.ref2Field;
            }
            set
            {
                this.ref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ref3
        {
            get
            {
                return this.ref3Field;
            }
            set
            {
                this.ref3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ref4
        {
            get
            {
                return this.ref4Field;
            }
            set
            {
                this.ref4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Ref5
        {
            get
            {
                return this.ref5Field;
            }
            set
            {
                this.ref5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IpToko
        {
            get
            {
                return this.ipTokoField;
            }
            set
            {
                this.ipTokoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ErrDetail
        {
            get
            {
                return this.errDetailField;
            }
            set
            {
                this.errDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CabangCredentials
    {
        
        private string kodeCabangField;
        
        private string ipAddressField;
        
        private System.DateTime logTimeField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KodeCabang
        {
            get
            {
                return this.kodeCabangField;
            }
            set
            {
                this.kodeCabangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IpAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LogTime
        {
            get
            {
                return this.logTimeField;
            }
            set
            {
                this.logTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportSales", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportSalesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public ReportSalesRequest()
        {
        }
        
        public ReportSalesRequest(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.Data = Data;
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportSalesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportSalesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReportSalesResult;
        
        public ReportSalesResponse()
        {
        }
        
        public ReportSalesResponse(byte[] ReportSalesResult)
        {
            this.ReportSalesResult = ReportSalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportStockol", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportStockolRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data;
        
        public ReportStockolRequest()
        {
        }
        
        public ReportStockolRequest(byte[] Data)
        {
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportStockolResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportStockolResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ReportStockolResult;
        
        public ReportStockolResponse()
        {
        }
        
        public ReportStockolResponse(string ReportStockolResult)
        {
            this.ReportStockolResult = ReportStockolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTask", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTaskRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public GetTaskRequest()
        {
        }
        
        public GetTaskRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTaskResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetTaskResult;
        
        public GetTaskResponse()
        {
        }
        
        public GetTaskResponse(byte[] GetTaskResult)
        {
            this.GetTaskResult = GetTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaskCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTaskCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public GetTaskCabRequest()
        {
        }
        
        public GetTaskCabRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaskCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTaskCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetTaskCabResult;
        
        public GetTaskCabResponse()
        {
        }
        
        public GetTaskCabResponse(byte[] GetTaskCabResult)
        {
            this.GetTaskCabResult = GetTaskCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrPrCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrPrCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public GetTrPrCabRequest()
        {
        }
        
        public GetTrPrCabRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrPrCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrPrCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetTrPrCabResult;
        
        public GetTrPrCabResponse()
        {
        }
        
        public GetTrPrCabResponse(byte[] GetTrPrCabResult)
        {
            this.GetTrPrCabResult = GetTrPrCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public GetFileInfoRequest()
        {
        }
        
        public GetFileInfoRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileInfoResult;
        
        public GetFileInfoResponse()
        {
        }
        
        public GetFileInfoResponse(byte[] GetFileInfoResult)
        {
            this.GetFileInfoResult = GetFileInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileInfoCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileInfoCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public GetFileInfoCabRequest()
        {
        }
        
        public GetFileInfoCabRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileInfoCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileInfoCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileInfoCabResult;
        
        public GetFileInfoCabResponse()
        {
        }
        
        public GetFileInfoCabResponse(byte[] GetFileInfoCabResult)
        {
            this.GetFileInfoCabResult = GetFileInfoCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACKTaskCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ACKTaskCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public ACKTaskCabRequest()
        {
        }
        
        public ACKTaskCabRequest(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.Data = Data;
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACKTaskCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ACKTaskCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ACKTaskCabResult;
        
        public ACKTaskCabResponse()
        {
        }
        
        public ACKTaskCabResponse(bool ACKTaskCabResult)
        {
            this.ACKTaskCabResult = ACKTaskCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACKFileInfoCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ACKFileInfoCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public ACKFileInfoCabRequest()
        {
        }
        
        public ACKFileInfoCabRequest(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.Data = Data;
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACKFileInfoCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ACKFileInfoCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ACKFileInfoCabResult;
        
        public ACKFileInfoCabResponse()
        {
        }
        
        public ACKFileInfoCabResponse(bool ACKFileInfoCabResult)
        {
            this.ACKFileInfoCabResult = ACKFileInfoCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportSalesCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportSalesCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang;
        
        public ReportSalesCabRequest()
        {
        }
        
        public ReportSalesCabRequest(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            this.Data = Data;
            this.CredToko = CredToko;
            this.CredCabang = CredCabang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportSalesCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReportSalesCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReportSalesCabResult;
        
        public ReportSalesCabResponse()
        {
        }
        
        public ReportSalesCabResponse(byte[] ReportSalesCabResult)
        {
            this.ReportSalesCabResult = ReportSalesCabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusTableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ListToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string KdCabang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NamaTable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Status;
        
        public GetStatusTableRequest()
        {
        }
        
        public GetStatusTableRequest(string ListToko, string KdCabang, string NamaTable, string Status)
        {
            this.ListToko = ListToko;
            this.KdCabang = KdCabang;
            this.NamaTable = NamaTable;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusTableResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusTableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetStatusTableResult;
        
        public GetStatusTableResponse()
        {
        }
        
        public GetStatusTableResponse(byte[] GetStatusTableResult)
        {
            this.GetStatusTableResult = GetStatusTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestoreTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RestoreTableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string KodeToko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string TblName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int DayInterval;
        
        public RestoreTableRequest()
        {
        }
        
        public RestoreTableRequest(string KodeToko, string TblName, int DayInterval)
        {
            this.KodeToko = KodeToko;
            this.TblName = TblName;
            this.DayInterval = DayInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestoreTableResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RestoreTableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RestoreTableResult;
        
        public RestoreTableResponse()
        {
        }
        
        public RestoreTableResponse(byte[] RestoreTableResult)
        {
            this.RestoreTableResult = RestoreTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadMaster", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadMasterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NamaTbl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime TglMin;
        
        public DownloadMasterRequest()
        {
        }
        
        public DownloadMasterRequest(string NamaTbl, System.DateTime TglMin)
        {
            this.NamaTbl = NamaTbl;
            this.TglMin = TglMin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadMasterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadMasterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadMasterResult;
        
        public DownloadMasterResponse()
        {
        }
        
        public DownloadMasterResponse(byte[] DownloadMasterResult)
        {
            this.DownloadMasterResult = DownloadMasterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadTblToko", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadTblTokoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConnectedServices_PosRT_Cabang.TokoCredentials CredToko;
        
        public DownloadTblTokoRequest()
        {
        }
        
        public DownloadTblTokoRequest(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko)
        {
            this.CredToko = CredToko;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadTblTokoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadTblTokoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadTblTokoResult;
        
        public DownloadTblTokoResponse()
        {
        }
        
        public DownloadTblTokoResponse(byte[] DownloadTblTokoResult)
        {
            this.DownloadTblTokoResult = DownloadTblTokoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquiryRetTok", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InquiryRetTokRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RequestRET;
        
        public InquiryRetTokRequest()
        {
        }
        
        public InquiryRetTokRequest(byte[] RequestRET)
        {
            this.RequestRET = RequestRET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquiryRetTokResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InquiryRetTokResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] InquiryRetTokResult;
        
        public InquiryRetTokResponse()
        {
        }
        
        public InquiryRetTokResponse(byte[] InquiryRetTokResult)
        {
            this.InquiryRetTokResult = InquiryRetTokResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadRetTok", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRetTokRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RequestRET;
        
        public UploadRetTokRequest()
        {
        }
        
        public UploadRetTokRequest(byte[] RequestRET)
        {
            this.RequestRET = RequestRET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadRetTokResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRetTokResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadRetTokResult;
        
        public UploadRetTokResponse()
        {
        }
        
        public UploadRetTokResponse(byte[] UploadRetTokResult)
        {
            this.UploadRetTokResult = UploadRetTokResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Query;
        
        public ExecuteQueryRequest()
        {
        }
        
        public ExecuteQueryRequest(byte[] Query)
        {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExecuteQueryResult;
        
        public ExecuteQueryResponse()
        {
        }
        
        public ExecuteQueryResponse(string ExecuteQueryResult)
        {
            this.ExecuteQueryResult = ExecuteQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTrPrCab", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTrPrCabRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TaskName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Toko;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Cmd;
        
        public InsertTrPrCabRequest()
        {
        }
        
        public InsertTrPrCabRequest(string TaskName, string Toko, byte[] Cmd)
        {
            this.TaskName = TaskName;
            this.Toko = Toko;
            this.Cmd = Cmd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTrPrCabResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTrPrCabResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertTrPrCabResult;
        
        public InsertTrPrCabResponse()
        {
        }
        
        public InsertTrPrCabResponse(string InsertTrPrCabResult)
        {
            this.InsertTrPrCabResult = InsertTrPrCabResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ServiceSoapChannel : ConnectedServices_PosRT_Cabang.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ConnectedServices_PosRT_Cabang.ServiceSoap>, ConnectedServices_PosRT_Cabang.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ChekVersionAsync()
        {
            return base.Channel.ChekVersionAsync();
        }
        
        public System.Threading.Tasks.Task<string> InitSchemaAsync()
        {
            return base.Channel.InitSchemaAsync();
        }
        
        public System.Threading.Tasks.Task InfoPosrtAsync(string KdToko)
        {
            return base.Channel.InfoPosrtAsync(KdToko);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ReportSalesAsync(ConnectedServices_PosRT_Cabang.ReportSalesRequest request)
        {
            return base.Channel.ReportSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesResponse> ReportSalesAsync(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.ReportSalesRequest inValue = new ConnectedServices_PosRT_Cabang.ReportSalesRequest();
            inValue.Data = Data;
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ReportSalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportStockolResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ReportStockolAsync(ConnectedServices_PosRT_Cabang.ReportStockolRequest request)
        {
            return base.Channel.ReportStockolAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportStockolResponse> ReportStockolAsync(byte[] Data)
        {
            ConnectedServices_PosRT_Cabang.ReportStockolRequest inValue = new ConnectedServices_PosRT_Cabang.ReportStockolRequest();
            inValue.Data = Data;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ReportStockolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetTaskAsync(ConnectedServices_PosRT_Cabang.GetTaskRequest request)
        {
            return base.Channel.GetTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskResponse> GetTaskAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.GetTaskRequest inValue = new ConnectedServices_PosRT_Cabang.GetTaskRequest();
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetTaskCabAsync(ConnectedServices_PosRT_Cabang.GetTaskCabRequest request)
        {
            return base.Channel.GetTaskCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTaskCabResponse> GetTaskCabAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.GetTaskCabRequest inValue = new ConnectedServices_PosRT_Cabang.GetTaskCabRequest();
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetTaskCabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTrPrCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetTrPrCabAsync(ConnectedServices_PosRT_Cabang.GetTrPrCabRequest request)
        {
            return base.Channel.GetTrPrCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetTrPrCabResponse> GetTrPrCabAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.GetTrPrCabRequest inValue = new ConnectedServices_PosRT_Cabang.GetTrPrCabRequest();
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetTrPrCabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetFileInfoAsync(ConnectedServices_PosRT_Cabang.GetFileInfoRequest request)
        {
            return base.Channel.GetFileInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoResponse> GetFileInfoAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.GetFileInfoRequest inValue = new ConnectedServices_PosRT_Cabang.GetFileInfoRequest();
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetFileInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetFileInfoCabAsync(ConnectedServices_PosRT_Cabang.GetFileInfoCabRequest request)
        {
            return base.Channel.GetFileInfoCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetFileInfoCabResponse> GetFileInfoCabAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.GetFileInfoCabRequest inValue = new ConnectedServices_PosRT_Cabang.GetFileInfoCabRequest();
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetFileInfoCabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKTaskCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ACKTaskCabAsync(ConnectedServices_PosRT_Cabang.ACKTaskCabRequest request)
        {
            return base.Channel.ACKTaskCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKTaskCabResponse> ACKTaskCabAsync(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.ACKTaskCabRequest inValue = new ConnectedServices_PosRT_Cabang.ACKTaskCabRequest();
            inValue.Data = Data;
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ACKTaskCabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKFileInfoCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ACKFileInfoCabAsync(ConnectedServices_PosRT_Cabang.ACKFileInfoCabRequest request)
        {
            return base.Channel.ACKFileInfoCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ACKFileInfoCabResponse> ACKFileInfoCabAsync(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.ACKFileInfoCabRequest inValue = new ConnectedServices_PosRT_Cabang.ACKFileInfoCabRequest();
            inValue.Data = Data;
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ACKFileInfoCabAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> ResetTableHOAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            return base.Channel.ResetTableHOAsync(CredToko, CredCabang);
        }
        
        public System.Threading.Tasks.Task<string> ResetTableCabAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang, string Jenis)
        {
            return base.Channel.ResetTableCabAsync(CredToko, CredCabang, Jenis);
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang, string KeyToko_IMSI)
        {
            return base.Channel.CheckConnectionAsync(CredToko, CredCabang, KeyToko_IMSI);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ReportSalesCabAsync(ConnectedServices_PosRT_Cabang.ReportSalesCabRequest request)
        {
            return base.Channel.ReportSalesCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ReportSalesCabResponse> ReportSalesCabAsync(byte[] Data, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            ConnectedServices_PosRT_Cabang.ReportSalesCabRequest inValue = new ConnectedServices_PosRT_Cabang.ReportSalesCabRequest();
            inValue.Data = Data;
            inValue.CredToko = CredToko;
            inValue.CredCabang = CredCabang;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ReportSalesCabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetStatusTableResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.GetStatusTableAsync(ConnectedServices_PosRT_Cabang.GetStatusTableRequest request)
        {
            return base.Channel.GetStatusTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.GetStatusTableResponse> GetStatusTableAsync(string ListToko, string KdCabang, string NamaTable, string Status)
        {
            ConnectedServices_PosRT_Cabang.GetStatusTableRequest inValue = new ConnectedServices_PosRT_Cabang.GetStatusTableRequest();
            inValue.ListToko = ListToko;
            inValue.KdCabang = KdCabang;
            inValue.NamaTable = NamaTable;
            inValue.Status = Status;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).GetStatusTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.RestoreTableResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.RestoreTableAsync(ConnectedServices_PosRT_Cabang.RestoreTableRequest request)
        {
            return base.Channel.RestoreTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.RestoreTableResponse> RestoreTableAsync(string KodeToko, string TblName, int DayInterval)
        {
            ConnectedServices_PosRT_Cabang.RestoreTableRequest inValue = new ConnectedServices_PosRT_Cabang.RestoreTableRequest();
            inValue.KodeToko = KodeToko;
            inValue.TblName = TblName;
            inValue.DayInterval = DayInterval;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).RestoreTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadMasterResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.DownloadMasterAsync(ConnectedServices_PosRT_Cabang.DownloadMasterRequest request)
        {
            return base.Channel.DownloadMasterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadMasterResponse> DownloadMasterAsync(string NamaTbl, System.DateTime TglMin)
        {
            ConnectedServices_PosRT_Cabang.DownloadMasterRequest inValue = new ConnectedServices_PosRT_Cabang.DownloadMasterRequest();
            inValue.NamaTbl = NamaTbl;
            inValue.TglMin = TglMin;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).DownloadMasterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadTblTokoResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.DownloadTblTokoAsync(ConnectedServices_PosRT_Cabang.DownloadTblTokoRequest request)
        {
            return base.Channel.DownloadTblTokoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.DownloadTblTokoResponse> DownloadTblTokoAsync(ConnectedServices_PosRT_Cabang.TokoCredentials CredToko)
        {
            ConnectedServices_PosRT_Cabang.DownloadTblTokoRequest inValue = new ConnectedServices_PosRT_Cabang.DownloadTblTokoRequest();
            inValue.CredToko = CredToko;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).DownloadTblTokoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.StatusToko> SendStatusAsync(ConnectedServices_PosRT_Cabang.StatusToko Status)
        {
            return base.Channel.SendStatusAsync(Status);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InquiryRetTokResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.InquiryRetTokAsync(ConnectedServices_PosRT_Cabang.InquiryRetTokRequest request)
        {
            return base.Channel.InquiryRetTokAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InquiryRetTokResponse> InquiryRetTokAsync(byte[] RequestRET)
        {
            ConnectedServices_PosRT_Cabang.InquiryRetTokRequest inValue = new ConnectedServices_PosRT_Cabang.InquiryRetTokRequest();
            inValue.RequestRET = RequestRET;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).InquiryRetTokAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.UploadRetTokResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.UploadRetTokAsync(ConnectedServices_PosRT_Cabang.UploadRetTokRequest request)
        {
            return base.Channel.UploadRetTokAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.UploadRetTokResponse> UploadRetTokAsync(byte[] RequestRET)
        {
            ConnectedServices_PosRT_Cabang.UploadRetTokRequest inValue = new ConnectedServices_PosRT_Cabang.UploadRetTokRequest();
            inValue.RequestRET = RequestRET;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).UploadRetTokAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> SendTokoUpAsync(string KodeCabang, string TotalToko, ConnectedServices_PosRT_Cabang.TokoCredentials CredToko, ConnectedServices_PosRT_Cabang.CabangCredentials CredCabang)
        {
            return base.Channel.SendTokoUpAsync(KodeCabang, TotalToko, CredToko, CredCabang);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ExecuteQueryResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.ExecuteQueryAsync(ConnectedServices_PosRT_Cabang.ExecuteQueryRequest request)
        {
            return base.Channel.ExecuteQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.ExecuteQueryResponse> ExecuteQueryAsync(byte[] Query)
        {
            ConnectedServices_PosRT_Cabang.ExecuteQueryRequest inValue = new ConnectedServices_PosRT_Cabang.ExecuteQueryRequest();
            inValue.Query = Query;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).ExecuteQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InsertTrPrCabResponse> ConnectedServices_PosRT_Cabang.ServiceSoap.InsertTrPrCabAsync(ConnectedServices_PosRT_Cabang.InsertTrPrCabRequest request)
        {
            return base.Channel.InsertTrPrCabAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_PosRT_Cabang.InsertTrPrCabResponse> InsertTrPrCabAsync(string TaskName, string Toko, byte[] Cmd)
        {
            ConnectedServices_PosRT_Cabang.InsertTrPrCabRequest inValue = new ConnectedServices_PosRT_Cabang.InsertTrPrCabRequest();
            inValue.TaskName = TaskName;
            inValue.Toko = Toko;
            inValue.Cmd = Cmd;
            return ((ConnectedServices_PosRT_Cabang.ServiceSoap)(this)).InsertTrPrCabAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57824/PosRealTime_Cabang_Service (2)/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57824/PosRealTime_Cabang_Service (2)/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
